// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu1a7B3ed1qB4PgT6Dw2Upefto2DdtZ60',
    appId: '1:680973787103:web:c968c0b7d251505abcee6a',
    messagingSenderId: '680973787103',
    projectId: 'fir-interview-19325',
    authDomain: 'fir-interview-19325.firebaseapp.com',
    storageBucket: 'fir-interview-19325.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9fKVJzAK6CqwUnNBxAcDVzciI0rKOp2s',
    appId: '1:680973787103:android:d059922709382c8fbcee6a',
    messagingSenderId: '680973787103',
    projectId: 'fir-interview-19325',
    storageBucket: 'fir-interview-19325.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGe7ZqpA4YiTgKQm62pC2aRD525jvWhpQ',
    appId: '1:680973787103:ios:635a278a26302530bcee6a',
    messagingSenderId: '680973787103',
    projectId: 'fir-interview-19325',
    storageBucket: 'fir-interview-19325.appspot.com',
    iosBundleId: 'com.flutter.interview.flutterInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGe7ZqpA4YiTgKQm62pC2aRD525jvWhpQ',
    appId: '1:680973787103:ios:3c6ab024beb80be7bcee6a',
    messagingSenderId: '680973787103',
    projectId: 'fir-interview-19325',
    storageBucket: 'fir-interview-19325.appspot.com',
    iosBundleId: 'com.flutter.interview.flutterInterview.RunnerTests',
  );
}
